version: '3'

services:
  db:
    image: postgres:11
    container_name: "db"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=project
      - POSTGRES_PASSWORD=project
      - POSTGRES_DB=project
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U project" ]

  server:
    container_name: "test-server"
    build:
      context: ./server
    environment:
      - PGDB_NAME=project
      - PGDB_USER=project
      - PGDB_PASSWORD=project
      - PGDB_HOST=db
      - PGDB_PORT=5432
    command: bash -c "python3 manage.py migrate && python3 manage.py && python3 manage.py clear_all_subdiv && python3 manage.py clear_all_users_exclude_admins && python3 manage.py create_users && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./server/:/code
    depends_on:
      - db
    links:
      - db

  client:
    container_name: "test-client"
    build: .
    ports:
      - "4200:4200"
    links:
      - server
    volumes:
      - ./client/src:/client/src

volumes:
  pgdata:
