# Generated by Django 3.2.6 on 2021-09-08 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subdivisions', '0001_initial'),
        ('employees', '0002_auto_20210905_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='subdivisions.subdivision', verbose_name='Подразделение'),
        ),
    ]
